---
title: "Draft Need Analysis - Colby and Bates"
author: "Laurie Baker and Jim Scott"
format: html
editor: visual
---

## Colby Semester-Long 1/2 Credit Course:

| Specific Context of the Teaching/Learning Situation                                                                                                                                                               |                                                       |
|:-----------------------------------|:-----------------------------------|
| How many students are in the class?                                                                                                                                                                               | 15-30                                                 |
| What is the course level?                                                                                                                                                                                         | Introductory                                          |
| How will the course be delivered? What modality?                                                                                                                                                                  | Lectures, Labs, Discussions                           |
| How frequent are the class meetings?                                                                                                                                                                              | 3 times per week                                      |
| How long are the class meetings?                                                                                                                                                                                  | 85 minutes                                            |
| What physical elements of the learning environment will affect the class? (e.g. fixed vs. flexible seating, whiteboard/blackboard space, oise levels, place on campus, technology available in the classroom etc? | Flexible seating, blackboard or whiteboard, projector |

| General Context of the Teaching/Learning Situation                           |                                                                                           |
|:-----------------------------------|:-----------------------------------|
| Is this course a general education requirement?                              | No                                                                                        |
| Is this course a prerequisite for other courses?                             | No, but it could be a gateway for Probability, Statistics and Bayesian Statistics classes |
| Other learning expectations placed on this course by the department?         | Fulfill the math short-term credit                                                        |
| Other learning expectations placed on this course by the college/university? | None                                                                                      |
| Other learning expectations placed on this course by the profession?         | None                                                                                      |
| Other learning expectations placed on this course by society?                | None                                                                                      |

| Nature of the Subject                                                    |                                                                                               |
|:-----------------------------------|:-----------------------------------|
| Is the subject primarily theoretical, practical, or a combination?       | Combination. The course will involve hands-on coding sessions, problem sets, and discussions. |
| Are there important changes or controversies occurring within the field? | Frequentist vs. Bayesian Statistics                                                           |

| Characteristics of the Learners                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|:-----------------------------------|:-----------------------------------|
| What are the life situations of the learners? (e.g. Working part-time? Full-time? Family? Professional goals? Extracurricular involvements (like collegiate athletics)? | Working part-time and extracurricular involvements                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| What prior knowledge, experiences, and initial feelings do students usually have about this subject?                                                                    | Students may have heard about the topic of Bayesian Statistics and/or have some exposure to probability from AP Statistics                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| What are the students’ learning goals and expectations for learning?                                                                                                    | Students who take this course will be curious about probability and Bayesian statistics, perhaps because they have come across the topics in other settings or because a professor, classmate or family member has recommended the topic. They will be interested in understanding: What Bayesian Statistics is, how it differs from frequentist statistics if they have taken statistics before, and how it can be used/applied to questions they are interested in. Students from majors outside Math and Statistics may be interested in gaining a higher-level general awareness of the above. |
| What are the demographics of your students? (e.g. Pell-eligible, race/ethnicity, gender, first gen, international students, etc.)                                       | Pell-eligible, range of race/ethnicities, gender, first gen, international students may all be in this course.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| What is the climate of the program, institution, or field of study?                                                                                                     | Math and Statistics can be viewed as challenging subjects, especially for those outside of those departments. At Colby this is a ½ credit course I don’t believe it will fully fulfill the math requirement. ½ credit courses tend to be like electives, so the course may attract students who are motivated to take the course and interested in the subject material.                                                                                                                                                                                                                           |
| What geopolitical contexts might be impacting your students?                                                                                                            | Ongoing conflicts (e.g. Palestine/Israel, Ukraine, Sudan). Natural disasters (e.g. Hurricane Helene).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |

## Bates College: 1/2 Credit, 3.5 week Short-term Course

| Specific Context of the Teaching/Learning Situation                                                                                                                                                                |                                                       |
|:-----------------------------------|:-----------------------------------|
| How many students are in the class?                                                                                                                                                                                | 15-30                                                 |
| What is the course level?                                                                                                                                                                                          | Introductory                                          |
| How will the course be delivered? What modality?                                                                                                                                                                   | Lectures, Labs, Discussions                           |
| How frequent are the class meetings?                                                                                                                                                                               | 3 times per week                                      |
| How long are the class meetings?                                                                                                                                                                                   | 85 minutes                                            |
| What physical elements of the learning environment will affect the class? (e.g. fixed vs. flexible seating, whiteboard/blackboard space, noise levels, place on campus, technology available in the classroom etc? | Flexible seating, blackboard or whiteboard, projector |

| General Context of the Teaching/Learning Situation                           |                                                                                           |
|:-----------------------------------|:-----------------------------------|
| Is this course a general education requirement?                              | No                                                                                        |
| Is this course a prerequisite for other courses?                             | No, but it could be a gateway for Probability, Statistics and Bayesian Statistics classes |
| Other learning expectations placed on this course by the department?         | Fulfill the math short-term credit                                                        |
| Other learning expectations placed on this course by the college/university? | None                                                                                      |
| Other learning expectations placed on this course by the profession?         | None                                                                                      |
| Other learning expectations placed on this course by society?                | None                                                                                      |

| Nature of the Subject                                                    |                                                                                               |
|:-----------------------------------|:-----------------------------------|
| Is the subject primarily theoretical, practical, or a combination?       | Combination. The course will involve hands-on coding sessions, problem sets, and discussions. |
| Are there important changes or controversies occurring within the field? | Frequentist vs. Bayesian Statistics                                                           |

| Characteristics of the Learners                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|:-----------------------------------|:-----------------------------------|
| What are the life situations of the learners? (e.g. Working part-time? Full-time? Family? Professional goals? Extracurricular involvements (like collegiate athletics)? | Working part-time and extracurricular involvements                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| What prior knowledge, experiences, and initial feelings do students usually have about this subject?                                                                    | Students may have heard about the topic of Bayesian Statistics and/or have some exposure to probability from AP Statistics                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| What are the students’ learning goals and expectations for learning?                                                                                                    | Students who take this course will be curious about probability and Bayesian statistics, perhaps because they have come across the topics in other settings or because a professor, classmate or family member has recommended the topic. They will be interested in understanding: What Bayesian Statistics is, how it differs from frequentist statistics if they have taken statistics before, and how it can be used/applied to questions they are interested in. Students from majors outside Math and Statistics may be interested in gaining a higher-level general awareness of the above. |
| What are the demographics of your students? (e.g. Pell-eligible, race/ethnicity, gender, first gen, international students, etc.)                                       | Pell-eligible, range of race/ethnicities, gender, first gen, international students may all be in this course.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| What is the climate of the program, institution, or field of study?                                                                                                     | Math and Statistics can be viewed as challenging subjects, especially for those outside of those departments. At Bates, because this is a ½ credit course I don’t believe it will fully fulfill the math requirement. ½ credit courses tend to be like electives, so the course may attract students who are motivated to take the course and interested in the subject material. Students may also feel safer taking the course if it has a title like “A Gentle Introduction to Bayesian Statistics”                                                                                             |
| What geopolitical contexts might be impacting your students?                                                                                                            | Ongoing conflicts (e.g. Palestine/Israel, Ukraine, Sudan). Natural disasters (e.g. Hurricane Helene).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
