---
title: "Syllabus"
author: "Jim Scott and Laurie Baker"
date: "10/04/2024"
format: html
editor: visual
---

## Syllabus

Bayesian statistics is an approach to data analysis that incorporates prior knowledge or beliefs with new evidence to make inferences. This differs from traditional statistics, which interprets probability as the long-term frequency of events and doesn’t explicitly incorporate any prior knowledge of the system being studied. Fundamental to both types of statistical analysis is probability. At its core, probability is a field of mathematics that attempts to model and quantify the uncertainty of an event or events. It helps us answer the question: “What is the likelihood that an event will occur?”. Probability is widely used in science, economics, forecasting, engineering, and many other fields to help us understand risk, improve designs, and make decisions.

In this course, we will explore the basics of probability and how it pertains to Bayesian statistics. We’ll focus on conceptual understanding, practical skills, and problem-solving abilities. We will also introduce the Bayesian framework for doing statistics, describe how it differs from traditional statistics, and perform statistical analyses using Bayesian methods using the software R and the integrated development environment, RStudio.

### Learning Goals:

-   Understand basic probability concepts and basic Bayesian concepts
-   Learn basic rules of probability and how to apply them
-   Develop a firm understanding of conditional probability and Bayes theorem
-   Explore common discrete and continuous probability distributions
-   Compare and contrast Bayesian methods with frequentist statistical methods
-   Use Bayes theorem to update probabilities with prior knowledge
-   Understand the basics concepts of likelihood, prior and posterior distributions
-   Perform Bayesian inference for a single proportion and simple linear regression
-   Create and interpret credible intervals
-   Use computational methods to perform analyses

### Resources and Technology

- Probability readings and problem sets will be drawn from [Stat 20](https://stat20.org) by Andrew Bray and colleagues at UC Berkeley.
- Bayesian statistics readings and exercises will be drawn from [Bayes Rules](https://www.bayesrulesbook.com/) by Alicia A. Johnson, Miles Q. Ott, and Mine Dogucu.

### Assessment

-   Weekly Quiz: 10%
-   Weekly Problem Set: 30%
-   Two Lab Write Ups: 50%
-   Participation: 10%
-   Final Project\*

\*A final project may be explored in the semester long half credit course.
